language: python

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-opencv

install:
  - "pip install --pre -r requirements.txt"

python:
  - "2.7"
script:
  - python main.py